jobs:
- job: macOS
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - task: InstallAppleCertificate@2
    inputs:
      certSecureFile: 'Application.p12'
      certPwd: 'pAVuCweV'
      keychain: 'temp'
  - task: InstallAppleCertificate@2
    inputs:
      certSecureFile: 'Installer.p12'
      certPwd: 'pAVuCweV'
      keychain: 'temp'
  - task: InstallSSHKey@0
    inputs:
      knownHostsEntry: 'github.com,192.30.252.130 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=='
      sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDI0VqriIHvLkS9KhRSbEWXW5K19RTfGFbZe9sS4HPGf1fcnOzZkO8+m2MOWKrOXRq1bvax8PL/2M8LbrhmMndmAlDtSbsu8HfWRN9JvQqPgxb3kOyeJw84NMoxZeem/wcycd0tN2Qd9KLK1W28Vnz++3LXh8UdpvYIM77GfG3bIDI2I7H2JNsoNtQxhM1jI8/nllFUYsrHVF2zYklZsqzf8IoX4SYYJ9EBSsZ+aYxUeD43P4bz5HxrXQnR0KI8bC9U1LLZSm8CzsnFsg9GP51hJVvcDGfl7H2wFJC3AYsByJ4IZpvAUeKcWUu++HywGb+lzs66hnNPE8DEKf14weAh rrabien@Rolands-Mac-Pro.local'
      sshKeySecureFile: 'id_rsa'
  - checkout: self
    submodules: true
    persistCredentials: true
  - script: Scripts/macci
    displayName: 'macOS Build'
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'macOS'
      targetPath: 'Scripts/bin/mac'
  - task: FtpUpload@2
    inputs:
      credentialsOption: 'serviceEndpoint'
      serverEndpoint: 'ftp_figbug_com'
      rootDirectory: 'Scripts/bin/mac'
      filePatterns: '**'
      remoteDirectory: '/home/socalabs/www/files'
      clean: false
      cleanContents: false
      preservePaths: false
      trustSSL: false        
- job: windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: InstallSSHKey@0
    inputs:
      knownHostsEntry: 'github.com,192.30.252.130 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=='
      sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDI0VqriIHvLkS9KhRSbEWXW5K19RTfGFbZe9sS4HPGf1fcnOzZkO8+m2MOWKrOXRq1bvax8PL/2M8LbrhmMndmAlDtSbsu8HfWRN9JvQqPgxb3kOyeJw84NMoxZeem/wcycd0tN2Qd9KLK1W28Vnz++3LXh8UdpvYIM77GfG3bIDI2I7H2JNsoNtQxhM1jI8/nllFUYsrHVF2zYklZsqzf8IoX4SYYJ9EBSsZ+aYxUeD43P4bz5HxrXQnR0KI8bC9U1LLZSm8CzsnFsg9GP51hJVvcDGfl7H2wFJC3AYsByJ4IZpvAUeKcWUu++HywGb+lzs66hnNPE8DEKf14weAh rrabien@Rolands-Mac-Pro.local'
      sshKeySecureFile: 'id_rsa'
  - checkout: self
    submodules: true
    persistCredentials: true
  - script: Scripts\pcci.bat
    displayName: 'Windows Build'
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'Windows'
      targetPath: 'Scripts/bin/win'
  - task: FtpUpload@2
    inputs:
      credentialsOption: 'serviceEndpoint'
      serverEndpoint: 'ftp_figbug_com'
      rootDirectory: 'Scripts/bin/win'
      filePatterns: '**'
      remoteDirectory: '/home/socalabs/www/files'
      clean: false
      cleanContents: false
      preservePaths: false
      trustSSL: false            
