name: Build ChannelMute - Linux
on:
  push:
    branches:
      - master
    tags:
      - 'channelmute_v*'
    paths:
      - 'plugins/ChannelMute/**'
jobs:
  build:
    name: Build ChannelMute - Linux
    runs-on: ubuntu-latest
    steps:
      - name: Fix up git URLs
        run: |
          echo -e '[url "https://github.com/"]\n  insteadOf = "git@github.com:"' >> ~/.gitconfig
        shell: bash
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install clang ninja-build git ladspa-sdk freeglut3-dev g++ libasound2-dev libcurl4-openssl-dev libfreetype6-dev libjack-jackd2-dev libx11-dev libxcomposite-dev libxcursor-dev libxinerama-dev libxrandr-dev mesa-common-dev webkit2gtk-4.0 juce-tools xvfb
      - name: Build plugin
        run: |
          # Build
          cd plugins/ChannelMute
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=OFF -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
          cmake --build build

          # Package
          mkdir -p ../../ci/bin
          cd ../../ci/bin
          mkdir -p lv2 vst vst3

          cp -R "../../plugins/ChannelMute/build/ChannelMute_artefacts/LV2/ChannelMute.lv2" lv2/
          cp -R "../../plugins/ChannelMute/build/ChannelMute_artefacts/VST/libChannelMute.so" "vst/ChannelMute.so"
          cp -R "../../plugins/ChannelMute/build/ChannelMute_artefacts/VST3/ChannelMute.vst3" vst3/

          # Create zip
          zip -r ChannelMute_Linux.zip vst/ChannelMute.so vst3/ChannelMute.vst3 lv2/ChannelMute.lv2

          # Upload to socalabs on release tag
          if [[ "$GITHUB_REF" == refs/tags/channelmute_v* ]]; then
            curl -F "files=@ChannelMute_Linux.zip" "https://socalabs.com/files/set.php?key=$APIKEY"
          fi
        shell: bash
        env:
          APIKEY: ${{ secrets.APIKEY }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ChannelMute_Linux
          path: ci/bin/*.zip
          retention-days: 30
