name: Build SFX8 - Windows
on:
  push:
    branches:
      - master
    paths:
      - 'plugins/SFX8/**'
jobs:
  build:
    name: Build SFX8 - Windows
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - name: Fix up git URLs
        run: |
          "[url `"https://github.com/`"]`n  insteadOf = `"git@github.com:`"" | Out-File -FilePath $env:USERPROFILE\.gitconfig -Append -Encoding UTF8
        shell: pwsh
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: recursive
      - name: Build plugin
        run: |
          # Build
          cd plugins/SFX8
          cmake -B build
          cmake --build build --config Release

          # Package
          New-Item -ItemType Directory -Force -Path "../../ci/bin"
          cd ../../ci/bin
          New-Item -ItemType Directory -Force -Path "vst"
          New-Item -ItemType Directory -Force -Path "vst3"

          Copy-Item "../../plugins/SFX8/build/SFX8_artefacts/Release/VST/SFX8.dll" "vst/"
          Copy-Item "../../plugins/SFX8/build/SFX8_artefacts/Release/VST3/SFX8.vst3" "vst3/" -Recurse

          # Create zip
          7z a SFX8_Win.zip vst/SFX8.dll vst3/SFX8.vst3
        shell: pwsh
        env:
          APIKEY: ${{ secrets.APIKEY }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SFX8_Windows
          path: ci/bin/*.zip
          retention-days: 30
