name: Build slCrossfeed - Linux
on:
  push:
    branches:
      - master
      - release
    paths:
      - 'plugins/slCrossfeed/**'
      - 'modules/**'
      - '.github/workflows/build_slCrossfeed_linux.yaml'
jobs:
  build:
    name: Build slCrossfeed - Linux
    runs-on: ubuntu-latest
    steps:
      - name: Fix up git URLs
        run: |
          echo -e '[url "https://github.com/"]\n  insteadOf = "git@github.com:"' >> ~/.gitconfig
        shell: bash
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install clang ninja-build git ladspa-sdk freeglut3-dev g++ libasound2-dev libcurl4-openssl-dev libfreetype6-dev libjack-jackd2-dev libx11-dev libxcomposite-dev libxcursor-dev libxinerama-dev libxrandr-dev mesa-common-dev webkit2gtk-4.0 juce-tools xvfb
      - name: Build plugin
        run: |
          # Build
          cd plugins/slCrossfeed
          cmake -B build -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
          cmake --build build --config Release

          # Package
          mkdir -p ../../ci/bin
          cd ../../ci/bin
          mkdir -p lv2 vst vst3

          cp -R "../../plugins/slCrossfeed/build/slCrossfeed_artefacts/LV2/slCrossfeed.lv2" lv2/
          cp -R "../../plugins/slCrossfeed/build/slCrossfeed_artefacts/VST/libslCrossfeed.so" "vst/slCrossfeed.so"
          cp -R "../../plugins/slCrossfeed/build/slCrossfeed_artefacts/VST3/slCrossfeed.vst3" vst3/

          # Create zip
          zip -r slCrossfeed_Linux.zip vst/slCrossfeed.so vst3/slCrossfeed.vst3 lv2/slCrossfeed.lv2

          # Upload to socalabs on release branch
          BRANCH="${GITHUB_REF##*/}"
          if [ "$BRANCH" = "release" ]; then
            curl -F "files=@slCrossfeed_Linux.zip" "https://socalabs.com/files/set.php?key=$APIKEY"
          fi
        shell: bash
        env:
          APIKEY: ${{ secrets.APIKEY }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: slCrossfeed_Linux
          path: ci/bin/*.zip
          retention-days: 30
