name: Build Expander - Linux
on:
  push:
    branches:
      - master
    paths:
      - 'plugins/Expander/**'
jobs:
  build:
    name: Build Expander - Linux
    runs-on: ubuntu-latest
    steps:
      - name: Fix up git URLs
        run: |
          echo -e '[url "https://github.com/"]\n  insteadOf = "git@github.com:"' >> ~/.gitconfig
        shell: bash
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install clang ninja-build git ladspa-sdk freeglut3-dev g++ libasound2-dev libcurl4-openssl-dev libfreetype6-dev libjack-jackd2-dev libx11-dev libxcomposite-dev libxcursor-dev libxinerama-dev libxrandr-dev mesa-common-dev webkit2gtk-4.0 juce-tools xvfb
      - name: Build plugin
        run: |
          # Build
          cd plugins/Expander
          cmake -B build -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
          cmake --build build --config Release

          # Package
          mkdir -p ../../ci/bin
          cd ../../ci/bin
          mkdir -p lv2 vst vst3

          cp -R "../../plugins/Expander/build/Expander_artefacts/LV2/Expander.lv2" lv2/
          cp -R "../../plugins/Expander/build/Expander_artefacts/VST/libExpander.so" "vst/Expander.so"
          cp -R "../../plugins/Expander/build/Expander_artefacts/VST3/Expander.vst3" vst3/

          # Create zip
          zip -r Expander_Linux.zip vst/Expander.so vst3/Expander.vst3 lv2/Expander.lv2
        shell: bash
        env:
          APIKEY: ${{ secrets.APIKEY }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Expander_Linux
          path: ci/bin/*.zip
          retention-days: 30
