name: Build Oscilloscope - Linux
on:
  push:
    branches:
      - master
    paths:
      - 'plugins/Oscilloscope/**'
jobs:
  build:
    name: Build Oscilloscope - Linux
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Fix up git URLs
        run: |
          echo -e '[url "https://github.com/"]\n  insteadOf = "git@github.com:"' >> ~/.gitconfig
        shell: bash
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install clang ninja-build git ladspa-sdk freeglut3-dev g++ libasound2-dev libcurl4-openssl-dev libfreetype6-dev libjack-jackd2-dev libx11-dev libxcomposite-dev libxcursor-dev libxinerama-dev libxrandr-dev mesa-common-dev webkit2gtk-4.0 juce-tools xvfb
      - name: Build plugin
        run: |
          # Build
          cd plugins/Oscilloscope
          cmake -B build -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
          cmake --build build --config Release

          # Package
          mkdir -p ../../ci/bin
          cd ../../ci/bin
          mkdir -p lv2 vst vst3

          cp -R "../../plugins/Oscilloscope/build/Oscilloscope_artefacts/LV2/Oscilloscope.lv2" lv2/
          cp -R "../../plugins/Oscilloscope/build/Oscilloscope_artefacts/VST/libOscilloscope.so" "vst/Oscilloscope.so"
          cp -R "../../plugins/Oscilloscope/build/Oscilloscope_artefacts/VST3/Oscilloscope.vst3" vst3/

          # Strip debug symbols
          strip vst/Oscilloscope.so
          strip vst3/Oscilloscope.vst3/Contents/x86_64-linux/Oscilloscope.so
          strip lv2/Oscilloscope.lv2/libOscilloscope.so

          # Create zip
          zip -r Oscilloscope_Linux.zip vst/Oscilloscope.so vst3/Oscilloscope.vst3 lv2/Oscilloscope.lv2
        shell: bash
        env:
          APIKEY: ${{ secrets.APIKEY }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Oscilloscope_Linux
          path: ci/bin/*.zip
          retention-days: 30
