name: Build WaveLooper - macOS
on:
  push:
    branches:
      - master
    tags:
      - 'wavelooper_v*'
jobs:
  build:
    name: Build WaveLooper - macOS
    runs-on: macos-latest
    steps:
      - name: Fix up git URLs
        run: |
          echo -e '[url "https://github.com/"]\n  insteadOf = "git@github.com:"' >> ~/.gitconfig
        shell: bash
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: recursive
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Build plugin
        run: |
          # Create a temp keychain
          echo "Create a keychain"
          security create-keychain -p nr4aGPyz Keys.keychain

          echo $APPLICATION | base64 -D -o /tmp/Application.p12
          echo $INSTALLER | base64 -D -o /tmp/Installer.p12

          security import /tmp/Application.p12 -t agg -k Keys.keychain -P aym9PKWB -A -T /usr/bin/codesign
          security import /tmp/Installer.p12 -t agg -k Keys.keychain -P aym9PKWB -A -T /usr/bin/codesign

          security list-keychains -s Keys.keychain
          security default-keychain -s Keys.keychain
          security unlock-keychain -p nr4aGPyz Keys.keychain
          security set-keychain-settings -l -u -t 13600 Keys.keychain
          security set-key-partition-list -S apple-tool:,apple: -s -k nr4aGPyz Keys.keychain

          DEV_APP_ID="Developer ID Application: Roland Rabien (3FS7DJDG38)"

          # Build
          cd plugins/WaveLooper
          cmake -B build -G Xcode
          cmake --build build --config Release

          # Package
          mkdir -p ../../ci/bin
          cd ../../ci/bin
          mkdir -p au vst vst3

          cp -R "../../plugins/WaveLooper/build/WaveLooper_artefacts/Release/AU/WaveLooper.component" au/
          cp -R "../../plugins/WaveLooper/build/WaveLooper_artefacts/Release/VST/WaveLooper.vst" vst/
          cp -R "../../plugins/WaveLooper/build/WaveLooper_artefacts/Release/VST3/WaveLooper.vst3" vst3/

          # Code sign
          codesign -s "$DEV_APP_ID" -v "vst/WaveLooper.vst" --options=runtime --timestamp --force
          codesign -s "$DEV_APP_ID" -v "vst3/WaveLooper.vst3" --options=runtime --timestamp --force
          codesign -s "$DEV_APP_ID" -v "au/WaveLooper.component" --options=runtime --timestamp --force

          # Notarize
          zip -r WaveLooper_Mac.zip vst/WaveLooper.vst vst3/WaveLooper.vst3 au/WaveLooper.component

          if [[ -n "$APPLE_USER" ]]; then
            xcrun notarytool submit --verbose --apple-id "$APPLE_USER" --password "$APPLE_PASS" --team-id "3FS7DJDG38" --wait --timeout 30m WaveLooper_Mac.zip

            rm WaveLooper_Mac.zip
            xcrun stapler staple vst/WaveLooper.vst
            xcrun stapler staple vst3/WaveLooper.vst3
            xcrun stapler staple au/WaveLooper.component
            zip -r WaveLooper_Mac.zip vst/WaveLooper.vst vst3/WaveLooper.vst3 au/WaveLooper.component
          fi

          # Upload to socalabs on release tag
          if [[ "$GITHUB_REF" == refs/tags/wavelooper_v* ]]; then
            curl -F "files=@WaveLooper_Mac.zip" "https://socalabs.com/files/set.php?key=$APIKEY"
          fi
        shell: bash
        env:
          APPLICATION: ${{ secrets.APPLICATION }}
          INSTALLER: ${{ secrets.INSTALLER }}
          APPLE_PASS: ${{ secrets.APPLE_PASS }}
          APPLE_USER: ${{ secrets.APPLE_USER }}
          APIKEY: ${{ secrets.APIKEY }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WaveLooper_macOS
          path: ci/bin/*.zip
          retention-days: 30
