name: Build EQ3 - Windows
on:
  push:
    branches:
      - master
    tags:
      - 'eq3_v*'
    paths:
      - 'plugins/EQ3/**'
jobs:
  build:
    name: Build EQ3 - Windows
    runs-on: windows-latest
    steps:
      - name: Fix up git URLs
        run: |
          "[url `"https://github.com/`"]`n  insteadOf = `"git@github.com:`"" | Out-File -FilePath $env:USERPROFILE\.gitconfig -Append -Encoding UTF8
        shell: pwsh
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: recursive
      - name: Build plugin
        run: |
          # Build
          cd plugins/EQ3
          cmake -B build
          cmake --build build --config Release

          # Package
          New-Item -ItemType Directory -Force -Path "../../ci/bin"
          cd ../../ci/bin
          New-Item -ItemType Directory -Force -Path "vst"
          New-Item -ItemType Directory -Force -Path "vst3"

          Copy-Item "../../plugins/EQ3/build/EQ3_artefacts/Release/VST/EQ3.dll" "vst/"
          Copy-Item "../../plugins/EQ3/build/EQ3_artefacts/Release/VST3/EQ3.vst3" "vst3/" -Recurse

          # Create zip
          7z a EQ3_Win.zip vst/EQ3.dll vst3/EQ3.vst3

          # Upload to socalabs on release tag
          if ("${{github.ref}}" -like "refs/tags/eq3_v*") {
            curl.exe -F "files=@EQ3_Win.zip" "https://socalabs.com/files/set.php?key=$env:APIKEY"
          }
        shell: pwsh
        env:
          APIKEY: ${{ secrets.APIKEY }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: EQ3_Windows
          path: ci/bin/*.zip
          retention-days: 30
