name: Build HugeGain - Windows
on:
  push:
    branches:
      - master
    tags:
      - 'hugegain_v*'
    paths:
      - 'plugins/HugeGain/**'
      - 'modules/**'
      - '.github/workflows/build_HugeGain_windows.yaml'
jobs:
  build:
    name: Build HugeGain - Windows
    runs-on: windows-latest
    steps:
      - name: Fix up git URLs
        run: |
          "[url `"https://github.com/`"]`n  insteadOf = `"git@github.com:`"" | Out-File -FilePath $env:USERPROFILE\.gitconfig -Append -Encoding UTF8
        shell: pwsh
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: recursive
      - name: Build plugin
        run: |
          # Build
          cd plugins/HugeGain
          cmake -B build
          cmake --build build --config Release

          # Package
          New-Item -ItemType Directory -Force -Path "../../ci/bin"
          cd ../../ci/bin
          New-Item -ItemType Directory -Force -Path "vst"
          New-Item -ItemType Directory -Force -Path "vst3"

          Copy-Item "../../plugins/HugeGain/build/HugeGain_artefacts/Release/VST/HugeGain.dll" "vst/"
          Copy-Item "../../plugins/HugeGain/build/HugeGain_artefacts/Release/VST3/HugeGain.vst3" "vst3/" -Recurse

          # Create zip
          7z a HugeGain_Win.zip vst/HugeGain.dll vst3/HugeGain.vst3

          # Upload to socalabs on release tag
          if ("${{github.ref}}" -like "refs/tags/hugegain_v*") {
            curl.exe -F "files=@HugeGain_Win.zip" "https://socalabs.com/files/set.php?key=$env:APIKEY"
          }
        shell: pwsh
        env:
          APIKEY: ${{ secrets.APIKEY }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: HugeGain_Windows
          path: ci/bin/*.zip
          retention-days: 30
