name: Release ToneGenerator - Linux
on:
  push:
    tags:
      - 'tonegenerator_v*'
jobs:
  build:
    name: Release ToneGenerator - Linux
    runs-on: ubuntu-latest
    steps:
      - name: Fix up git URLs
        run: |
          echo -e '[url "https://github.com/"]\n  insteadOf = "git@github.com:"' >> ~/.gitconfig
        shell: bash
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install clang ninja-build git ladspa-sdk freeglut3-dev g++ libasound2-dev libcurl4-openssl-dev libfreetype6-dev libjack-jackd2-dev libx11-dev libxcomposite-dev libxcursor-dev libxinerama-dev libxrandr-dev mesa-common-dev webkit2gtk-4.0 juce-tools xvfb
      - name: Build plugin
        run: |
          # Build
          cd plugins/ToneGenerator
          cmake -B build -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
          cmake --build build --config Release

          # Package
          mkdir -p ../../ci/bin
          cd ../../ci/bin
          mkdir -p lv2 vst vst3

          cp -R "../../plugins/ToneGenerator/build/ToneGenerator_artefacts/LV2/ToneGenerator.lv2" lv2/
          cp -R "../../plugins/ToneGenerator/build/ToneGenerator_artefacts/VST/libToneGenerator.so" "vst/ToneGenerator.so"
          cp -R "../../plugins/ToneGenerator/build/ToneGenerator_artefacts/VST3/ToneGenerator.vst3" vst3/

          # Create zip
          zip -r ToneGenerator_Linux.zip vst/ToneGenerator.so vst3/ToneGenerator.vst3 lv2/ToneGenerator.lv2

          # Upload to socalabs on release tag
          if [[ "$GITHUB_REF" == refs/tags/tonegenerator_v* ]]; then
            curl -F "files=@ToneGenerator_Linux.zip" "https://socalabs.com/files/set.php?key=$APIKEY"
          fi
        shell: bash
        env:
          APIKEY: ${{ secrets.APIKEY }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ToneGenerator_Linux
          path: ci/bin/*.zip
          retention-days: 30
