name: Release GraphicEQ - Windows
on:
  push:
    tags:
      - 'graphiceq_v*'
jobs:
  build:
    name: Release GraphicEQ - Windows
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - name: Fix up git URLs
        run: |
          "[url `"https://github.com/`"]`n  insteadOf = `"git@github.com:`"" | Out-File -FilePath $env:USERPROFILE\.gitconfig -Append -Encoding UTF8
        shell: pwsh
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: recursive
      - name: Build plugin
        run: |
          # Build
          cd plugins/GraphicEQ
          cmake -B build
          cmake --build build --config Release

          # Package
          New-Item -ItemType Directory -Force -Path "../../ci/bin"
          cd ../../ci/bin
          New-Item -ItemType Directory -Force -Path "vst"
          New-Item -ItemType Directory -Force -Path "vst3"

          Copy-Item "../../plugins/GraphicEQ/build/GraphicEQ_artefacts/Release/VST/GraphicEQ.dll" "vst/"
          Copy-Item "../../plugins/GraphicEQ/build/GraphicEQ_artefacts/Release/VST3/GraphicEQ.vst3" "vst3/" -Recurse

          # Create zip
          7z a GraphicEQ_Win.zip vst/GraphicEQ.dll vst3/GraphicEQ.vst3

          # Upload to socalabs on release tag
          if ("${{github.ref}}" -like "refs/tags/graphiceq_v*") {
            curl.exe -F "files=@GraphicEQ_Win.zip" "https://socalabs.com/files/set.php?key=$env:APIKEY"
          }
        shell: pwsh
        env:
          APIKEY: ${{ secrets.APIKEY }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GraphicEQ_Windows
          path: ci/bin/*.zip
          retention-days: 30
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ci/bin/*.zip
